version: "3.9"

services:
  mariadb:
    image: mariadb
    build:
      context: requirements/mariadb
      args:
        - MYSQL_ROOT_PASSWORD
        - DATABASE_NAME
        - DATABASE_USER
        - DATABASE_PASSWORD
    container_name: mariadb
    networks:
      - inception_network
    volumes:
      - mariadb:/var/lib/mysql
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      start_period: 20s

  wordpress:
    image: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    build:
      context: requirements/wordpress
    environment:
      - DATABASE_NAME
      - DATABASE_USER
      - DATABASE_PASSWORD
      - DATABASE_HOST
      - DOMAIN_NAME
      - WP_TITLE
      - WP_ADMIN_NAME
      - WP_ADMIN_PASS
      - WP_ADMIN_EMAIL
      - WP_USER_NAME
      - WP_USER_PASS
      - WP_USER_EMAIL
    container_name: wordpress
    networks:
      - inception_network
    volumes:
      - wordpress:/data/wordpress
    restart: on-failure

  nginx:
    image: nginx
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
    container_name: nginx
    networks:
      - inception_network
    ports:
      - 443:443
    volumes:
      - wordpress:/data/wordpress
    restart: on-failure

networks:
  inception_network:
    name: inception_network
    driver: bridge

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/pmitsuko/data/mariadb

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/pmitsuko/data/wordpress
